source ~/.config/nvim/vim/settings.vim
source ~/.config/nvim/vim/plugins.vim
source ~/.config/nvim/vim/theme.vim
source ~/.config/nvim/vim/barbar.vim
source ~/.config/nvim/vim/rainbow-config.vim
source ~/.config/nvim/vim/vista-config.vim
source ~/.config/nvim/vim/lighline-config.vim
source ~/.config/nvim/vim/telescope-config.vim
source ~/.config/nvim/vim/startify.vim
luafile ~/.config/nvim/lua/plugin/lsp-config.lua
luafile ~/.config/nvim/lua/plugin/compe-config.lua
luafile ~/.config/nvim/lua/plugin/tree-sitter-config.lua
luafile ~/.config/nvim/lua/plugin/hlslens-config.lua
luafile ~/.config/nvim/lua/plugin/telescope.lua
" luafile ~/.config/nvim/lua/plugin/symbols-outline-config.lua
luafile ~/.config/nvim/lua/plugin/tree.lua
luafile ~/.config/nvim/lua/plugin/gitsigns-config.lua
luafile ~/.config/nvim/lua/plugin/vim-sneak.lua
source ~/.config/nvim/vim/remaps.vim
